<?php

function gmapslivesearch_variable_info($options) {
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_ADDRESS_SEARCH_LABEL] = array(
    'title' => t('Gmaps: TextBox address label'),
    'description' => t('Label for field address search on buy online'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_ADDRESS_SEARCH_LABEL_MOBILE] = array(
    'title' => t('Gmaps: TextBox address label (mobile)'),
    'description' => t('Label for field address search on buy online'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_SEARCH_LABEL] = array(
    'title' => t('Gmaps: Select stores label'),
    'description' => t('Label for field store on buy online'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_SEARCH_LABEL_MOBILE] = array(
    'title' => t('Gmaps: Select stores label(mobile)'),
    'description' => t('Label for field store on buy online'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELDSET_MAPS_GREAT_DISTANCE_MESSAGE] = array(
    'title' => t('Gmaps: Great distance message'),
    'description' => t('Message that appears when the stores on Find a Store are too far away.'),
    'localize' => TRUE
  );
    $variable[GMAPSLIVESEARCH_FIELDSET_MAPS_GREAT_DISTANCE_MESSAGE_MOBILE] = array(
    'title' => t('Gmaps: Great distance message (mobile)'),
    'description' => t('Message that appears when the stores on Find a Store are too far away.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_ADDRESS_SEARCH_LABEL] = array(
    'title' => t('Gmaps: address search label'),
    'description' => t('Label for field address search on buy online'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_ADDRESS_SEARCH_LABEL_MOBILE] = array(
    'title' => t('Gmaps: address search label (mobile)'),
    'description' => t('Label for field address search on buy online'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_SEARCH_LABEL] = array(
    'title' => t('Gmaps: select stores label'),
    'description' => t('Label for field store on buy online'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_SEARCH_LABEL_MOBILE] = array(
    'title' => t('Gmaps: select stores label (mobile)'),
    'description' => t('Label for field store on buy online'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_FIND_STORE_BTN] = array(
    'title' => t('Gmaps: search button text and title'),
    'description' => t('Search button text and title for the Find a Store box'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_FIND_STORE_BTN_MOBILE] = array(
    'title' => t('Gmaps: search button text and title (mobile)'),
    'description' => t('Search button text and title for the Find a Store box'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_ADDRESS_SEARCH_DESC] = array(
    'title' => t('Gmaps: Buy online address description'),
    'description' => t('Description for field address on buy online box'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_ADDRESS_SEARCH_DESC_MOBILE] = array(
    'title' => t('Gmaps: Buy online address description (mobile)'),
    'description' => t('Description for field address on buy online box'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_SEARCH_DESC] = array(
    'title' => t('Gmaps: Buy online store description'),
    'description' => t('Description for field store on buy online box'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_SEARCH_DESC_MOBILE] = array(
    'title' => t('Gmaps: Buy online store description (mobile)'),
    'description' => t('Description for field store on buy online box'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_ADDRESS_FIELD_LABEL] = array(
    'title' => t('Gmaps: Buy online address field label'),
    'description' => t('Label for address field on buy online box.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_ADDRESS_FIELD_LABEL_MOBILE] = array(
    'title' => t('Gmaps: Buy online address field label (mobile)'),
    'description' => t('Label for address field on buy online box.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_SEARCH_FIELD_LABEL] = array(
    'title' => t('Gmaps: Buy online store field label'),
    'description' => t('Label for store field on buy online box.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_STORE_SEARCH_FIELD_LABEL_MOBILE] = array(
    'title' => t('Gmaps: Buy online store field label (mobile)'),
    'description' => t('Label for store field on buy online box.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_ONLINE_BTN] = array(
    'title' => t('Gmaps: Go button text and title'),
    'description' => t('Go button text and title for the Buy Online box.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_ONLINE_BTN_MOBILE] = array(
    'title' => t('Gmaps: Go button text and title (mobile)'),
    'description' => t('Go button text and title for the Buy Online box.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_TITLE] = array(
    'title' => t('Gmaps: buy now page title'),
    'description' => t('Title for Gmaps live search page'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_TITLE_MOBILE] = array(
    'title' => t('Gmaps: buy now page page title (mobile)'),
    'description' => t('Title for Gmaps live search page'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_ADDRESS_SEARCH_DESC] = array(
    'title' => t('Gmaps: Where to buy page address description'),
    'description' => t('Description for field address on where to buy page.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_ADDRESS_SEARCH_DESC_MOBILE] = array(
    'title' => t('Gmaps: Where to buy page address description (mobile)'),
    'description' => t('Description for field address on where to buy page.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_STORE_SEARCH_DESC] = array(
    'title' => t('Gmaps: Where to buy page address description'),
    'description' => t('Description for field address on where to buy page.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_STORE_SEARCH_DESC_MOBILE] = array(
    'title' => t('Gmaps: Where to buy page address description (mobile)'),
    'description' => t('Description for field address on where to buy page.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_TITLE_TEXT] = array(
    'title' => t('Gmaps: Where to buy page title'),
    'description' => t('Page title for where to buy section.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_TITLE_TEXT_MOBILE] = array(
    'title' => t('Gmaps: Where to buy page title (mobile)'),
    'description' => t('Page title for where to buy section.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_SUBTITLE_TEXT] = array(
    'title' => t('Gmaps: Where to buy page subtitle'),
    'description' => t('Page subtitle for where to buy section.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_SUBTITLE_TEXT_MOBILE] = array(
    'title' => t('Gmaps: Where to buy page subtitle (mobile)'),
    'description' => t('Page subtitle for where to buy section.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_ADDRESS_FIELD_LABEL] = array(
    'title' => t('Gmaps: Where to buy address field label'),
    'description' => t('Label for address field on Where to buy page.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_ADDRESS_FIELD_LABEL_MOBILE] = array(
    'title' => t('Gmaps: Where to buy address field label (mobile)'),
    'description' => t('Label for address field on Where to buy page.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_STORE_FIELD_LABEL] = array(
    'title' => t('Gmaps: Where to buy store field label'),
    'description' => t('Label for store field on Where to buy page.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_NOW_PAGE_STORE_FIELD_LABEL_MOBILE] = array(
    'title' => t('Gmaps: Where to buy store field label (mobile)'),
    'description' => t('Label for store field on Where to buy page.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_FIELD_BUY_ONLINE_BTN_PAGE_MOBILE] = array(
    'title' => t('Gmaps: Buy Online - \'Go\' button text and title (mobile)'),
    'description' => t('\'Go\' button text and title for the Buy Online box.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_ONLINE_BTN_MAP_MOBILE] = array(
    'title' => t('Gmaps: Buy Online - \'Show map\' button text and title (mobile)'),
    'description' => t('\'Show map\' button text and title for the Buy Online box.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_FIELD_BUY_ONLINE_BTN_LIST_MOBILE] = array(
    'title' => t('Gmaps: Buy Online - \'Show list\' button text and title (mobile)'),
    'description' => t('\'Show list\' button text and title for the Buy Online box.'),
    'localize' => TRUE
  );
  
  $variable[GMAPSLIVESEARCH_ERROR_MESSAGE_ADDRESS_FIELD] = array(
    'title' => t('Gmaps: Address Error Message'),
    'description' => t('Error message for the address field.'),
    'localize' => TRUE
  );
  $variable[GMAPSLIVESEARCH_ERROR_MESSAGE_ADDRESS_FIELD_MOBILE] = array(
    'title' => t('Gmaps: Address Error Message (mobile)'),
    'description' => t('Error message for the address field.'),
    'localize' => TRUE
  );  

  return $variable;
}
