<?php
if (!defined('OMNITURE_PREFIX')) {
  define('OMNITURE_PREFIX', 'omniture_by_content');
}

/**
 * Implementation of hook_menu().
 */
function omniture_by_content_menu() {

  $items['admin/config/omniture/' . OMNITURE_PREFIX] = array(
    'title' => 'Mobile Page Load',
    'description' => 'Omniture Pfizer Mobile',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(OMNITURE_PREFIX . '_guide_form'),
    'access arguments' => array('administer omniture configuration'),
    'file' => OMNITURE_PREFIX . '.admin.inc',
   );
  
  $items['admin/config/omniture/' . OMNITURE_PREFIX . '/guide'] = array(
    'title' => 'User Guide',
    'description' => 'Omniture Pfizer Mobile Guide . ',
    'type' => MENU_DEFAULT_LOCAL_TASK
  );

  $items['admin/config/omniture/' . OMNITURE_PREFIX . '/onload'] = array(
    'title' => 'Java Script Settings',
    'description' => 'Adjust Omniture Pfizer Mobile options . ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(OMNITURE_PREFIX . '_js_form'),
    'access arguments' => array('administer omniture configuration'),
    'file' => OMNITURE_PREFIX . '.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function omniture_by_content_permission() {

  return array(
    'track omniture_by_content' => array(
      'title' => t('Use Omniture Fields Value por On Load Events'),
    ),
	);

}

/**
 * Implementation of hook_node_view().
 
 */ 

function omniture_by_content_node_view($node, $view_mode, $langcode) {
  global $user;
  
  if (user_access('track omniture_by_content') && $user->uid != 1 ) {
    if (isset($node->field_omniture_page_name_value) && !empty($node->field_omniture_page_name_value)) {
      $omniture_by_content_value = trim($node->field_omniture_page_name_value[$node->language][0]['value']);
      if (!empty($omniture_by_content_value)) {
        drupal_add_js(array('omniture' => array('pageName' => $omniture_by_content_value) ), array('type' => 'setting', 'cache' => FALSE));
        $output = variable_get(OMNITURE_PREFIX . '_selectors_javascript');
        drupal_add_js($output, array('type' => 'inline', 'scope' => 'footer', 'weight' => 50000));
      }
    }
  }
}